open_pdf_command:
  Windows: '"C:\Program Files\Adobe\Acrobat DC\Acrobat\Acrobat.exe" /A "page=PAGE_NUM=OpenActions" "PDF_PATH"'
  Linux: okular --unique -p PAGE_NUM PDF_PATH
bookxnote_root: E:\学习资料\bookxnote\notebooks
